package rct

// Rides in the order they're used in the game
var RIDENAMES = []string{
	"Spiral Roller coaster",
	"Stand Up Coaster",
	"Suspended Swinging",
	"Inverted",
	"Steel Mini Coaster",
	"Mini Railroad",
	"Monorail",
	"Mini Suspended Coaster",
	"Bumper Boats",
	"Wooden Wild Mine/Mouse",
	"Steeplechase/Motorbike/Soap Box Derby",
	"Car Ride",
	"Launched Freefall",
	"Bobsleigh Coaster",
	"Observation Tower",
	"Looping Roller Coaster",
	"Dinghy Slide",
	"Mine Train Coaster",
	"Chairlift",
	"Corkscrew Roller Coaster",
	"Maze",
	"Spiral Slide",
	"Go Karts",
	"Log Flume",
	"River Rapids",
	"Bumper Cars",
	"Pirate Ship",
	"Swinging Inverter Ship",
	"Food Stall",
	"(none)",
	"Drink Stall",
	"(none)",
	"Shop (all types)",
	"Merry Go Round",
	"Balloon Stall (maybe)",
	"Information Kiosk",
	"Bathroom",
	"Ferris Wheel",
	"Motion Simulator",
	"3D Cinema",
	"Gravitron",
	"Space Rings",
	"Reverse Freefall Coaster",
	"Elevator",
	"Vertical Drop Roller Coaster",
	"ATM",
	"Twist",
	"Haunted House",
	"First Aid",
	"Circus Show",
	"Ghost Train",
	"Twister Roller Coaster",
	"Wooden Roller Coaster",
	"Side-Friction Roller Coaster",
	"Wild Mouse",
	"Multi Dimension Coaster",
	"(none)",
	"Flying Roller Coaster",
	"(none)",
	"Virginia Reel",
	"Splash Boats",
	"Mini Helicopters",
	"Lay-down Roller Coaster",
	"Suspended Monorail",
	"(none)",
	"Reverser Roller Coaster",
	"Heartline Twister Roller Coaster",
	"Mini Golf",
	"Giga Coaster",
	"Roto-Drop",
	"Flying Saucers",
	"Crooked House",
	"Monorail Cycles",
	"Compact Inverted Coaster",
	"Water Coaster",
	"Air Powered Vertical Coaster",
	"Inverted Hairpin Coaster",
	"Magic Carpet",
	"Submarine Ride",
	"River Rafts",
	"(none)",
	"Enterprise",
	"(none)",
	"(none)",
	"(none)",
	"(none)",
	"Inverted Impulse Coaster",
	"Mini Roller Coaster",
	"Mine Ride",
	"LIM Launched Roller Coaster",
}
